version: "3"
services:

	mongo:
    		image: mongo
		container_name: mongo-docker
		network-mode: host 
		environment:
         	 - MONGO_DATA_DIR=/data/db
        	 - MONGO_LOG_DIR=/dev/null
        	volumes:
         	 - ./data/db:/data/db
       		ports:
           	 - 27017:27017
        	command: mongod --smallfiles --logpath=/dev/null # --quiet
		restart: always
	
	config-server:
		image: config-server
        	build: config-server/
		restart: always
		network-mode: host
        	container_name: config-server-docker
		depends-on:
  		ports:
            	 - 8086:8086

	muzixapp:
		image: muzixapp
        	build: muzixapp/
		restart: always
		network-mode: host
        	container_name: muzixapp-docker
		depends-on:
		 - mongo
		 - config-server
       		ports:
            	 - 8082:8082

	userapp:
		image: userapp
        	build: userapp/
		restart: always
		network-mode: host
        	container_name: userapp-docker
		depends-on:
		 - mongo
		 - config-server
       		ports:
            	 - 8083:8083
        apigateway: 
		image: apigateway
        	build: APIgateway/
		restart: always
		network-mode: host
        	container_name: apigateway-docker
		depends-on:
		 - muzixapp
		 - userapp
       		ports:
            	 - 8085:8085
		expose:
		- 8085

	eureka-server: 
		image: eureka-server
        	build: eurekaserver/
		restart: always
		network-mode: host
        	container_name: eureka-server-docker
       		ports:
            	 - 8761:8761



